"""Regenerate docs/demo-trace.md: a real MCP exchange over Streamable HTTP against
the connector, with ConnectWise and IT Glue replaced by the synthetic fixtures.

Run:  python scripts/demo_trace.py        (CI runs it and fails if the file changes)
"""

from __future__ import annotations

import itertools
import json
import logging
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "tests"), str(ROOT / "src")]

from handover.audit import AuditLog  # noqa: E402
from support import FIXED_TIME, McpSession, start  # noqa: E402

logging.disable(logging.INFO)
counter = itertools.count(1)
AuditLog.new_correlation_id = staticmethod(lambda: f"demo-{next(counter):04d}")  # deterministic for the trace

STEPS = [
    ("The technician names a client that exists twice", "resolve_client", {"query": "Summit Accounting"}),
    ("The technician names the client of the ticket", "resolve_client", {"query": "Northfield"}),
    ("Open tickets for that client", "list_open_tickets", {"client_ref": "CL-0142"}),
    ("Everything needed to hand over ticket 48211", "get_ticket_context", {"client_ref": "CL-0142", "ticket_id": 48211}),
    ("The approved runbook excerpt", "get_document_excerpt", {"client_ref": "CL-0142", "document_id": 77001}),
    ("A runbook this technician is not approved for", "get_document_excerpt", {"client_ref": "CL-0142", "document_id": 77002}),
]


def main() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        srv = start(Path(tmp))
        try:
            s = McpSession(srv.url, srv.token("tech-alice"))
            assert s.initialize().status_code == 200
            tools = s.rpc("tools/list").json()["result"]["tools"]
            results = []
            for title, tool, args in STEPS:
                r = s.rpc("tools/call", {"name": tool, "arguments": args})
                results.append((title, tool, args, r.json()))
            audit = [json.dumps({k: v for k, v in rec.items() if k != "ts"}, sort_keys=True) for rec in srv.app.audit.records]
            upstream = srv.transport.requests
            assert srv.transport.violations == [], srv.transport.violations
        finally:
            srv.stop()

    out = [
        "# Demo trace (generated)",
        "",
        "Generated by `scripts/demo_trace.py` and checked by CI: the job regenerates this file and fails if it differs.",
        "Real MCP JSON-RPC over Streamable HTTP against the connector in this repository, authenticated as the",
        "synthetic technician `tech-alice`. ConnectWise PSA and IT Glue are the synthetic fixtures in `fixtures/`.",
        f"Timestamps are pinned to {FIXED_TIME} and correlation IDs are sequential so the file is reproducible.",
        "No real client data, no real credentials, no model call.",
        "",
        "## Tools advertised",
        "",
        "| Tool | Title | readOnlyHint |",
        "|---|---|---|",
    ]
    for t in tools:
        out.append(f"| `{t['name']}` | {t.get('title', '')} | {t['annotations']['readOnlyHint']} |")
    for i, (title, tool, args, body) in enumerate(results, 1):
        result = body["result"]
        payload = result.get("structuredContent") or json.loads(result["content"][0]["text"])
        out += ["", f"## {i}. {title}", "", f"`tools/call` **{tool}**", "", "```json",
                json.dumps(args, indent=2), "```", "", "Result:", "", "```json",
                json.dumps(payload, indent=2, ensure_ascii=False), "```"]
    out += ["", "## Upstream requests made (method, path, query, PSA credential used)", "", "```"]
    for r in upstream:
        q = "&".join(f"{k}={v}" for k, v in r["query"].items())
        out.append(f"{r['system']:<11} {r['method']} {r['path']}{'?' + q if q else ''}" + (f"   [as {r['credential']}]" if r["credential"] else ""))
    out += ["```", "", "## Audit records (timestamps omitted)", "", "```"] + audit + ["```", ""]
    target = ROOT / "docs" / "demo-trace.md"
    target.write_text("\n".join(out))
    print(f"wrote {target.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
